on:
  workflow_call:
name: Teste de aplicacao
runs:
  using: 'composite'
  steps:
    - name: Setup PHP
      if: ${{ github.job}} == 'test'
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Instalar dependencias e composer
      if: ${{ github.job}} == 'test'
      shell: bash
      run: |
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php composer-setup.php --install-dir=/usr/local/bin --filename=composer --quiet
        php -r "unlink('composer-setup.php');"
        composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Executar Tests
      if: ${{ github.job}} == 'test'
      shell: bash
      run: vendor/bin/phpunit --no-interaction --coverage-clover=coverage.xml

      ##################################################################################################
      ################################### BUILD DOCKER IMAGE ###########################################
      ##################################################################################################

    - name: Docker Login
      if: ${{ github.job}} == 'build'
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set tags
      if: ${{ github.job}} == 'build'
      id: tags
      run: |
        echo "LATEST_TAG=misticaai1/misticaai:latest" >> $GITHUB_ENV
        echo "RUNNER_TAG=misticaai1/misticaai:${{ github.run_number }}" >> $GITHUB_ENV

    - name: Build and push Docker image
      if: ${{ github.job}} == 'build'
      uses: docker/build-push-action@v6.9.0
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          ${{ env.LATEST_TAG }}
          ${{ env.RUNNER_TAG }}