name: Pipeline PHP

on:
  workflow_dispatch:

jobs:
  call-reusable:
    name: Job
    permissions:
      contents: read
      security-events: write
      actions: read
    uses: guuimartins/estuda.com/.github/workflows/reusable.yml@main
    secrets: inherit