name: Reusable Workflow

on:
  workflow_call:

env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Run tests
        uses: ./.github/workflows/actions/php

  vulnerabilidade:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
        
      - name: Analise de vulnerabilidade
        uses: ./.github/workflows/actions/trivy

  build:
    needs: vulnerabilidade
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Build Docker image
        uses: ./.github/workflows/actions/php