name: Reusable Workflow

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Run tests
        uses: ./.github/actions/PHP

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Build Docker image
        uses: ./.github/actions/PHP

        
  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
    
  #   steps:
  #     - name: Deploy
  #       run: echo "Deploying to ${{ inputs.environment }}"
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.token }}