name: Reusable Workflow

on:
  workflow_call:

env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Run tests
        uses: ./.github/workflows/actions/php

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Build Docker image
        uses: ./.github/workflows/actions/php
        with:
          docker_username: ${{ env.docker_username }}
          docker_password: ${{ env.docker_password }}

        
  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
    
  #   steps:
  #     - name: Deploy
  #       run: echo "Deploying to ${{ inputs.environment }}"
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.token }}